baseURL = 'https://opetit.fr/'
languageCode = 'fr-FR'
title = 'Olivier Petit'

[menus]

  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 30

  [[menus.main]]
    name = 'CVPrompt'
    pageRef = '/cvprompt'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
