baseURL = 'https://opetit.fr/'
languageCode = 'fr-FR'
title = 'Olivier Petit'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = 'Blog'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 30

  [[menus.main]]
    name = 'Contact'
    pageRef = '/contact'
    weight = 40


[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
