name: build-and-deploy

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      HUGO_VERSION: 0.146.0

    steps:
      - name: Install lftp
        run: sudo apt update && sudo apt install lftp

      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Install Dart Sass
        run: sudo snap install dart-sass

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Hugo App
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          env API_URL=${{ secrets.API_URL }} hugo --minify
          
      - name: Add server SSH key to known_hosts
        run: |
          mkdir -p ~/.ssh && ssh-keyscan -H ${{ secrets.SFTP_SERVER_NAME }} >> ~/.ssh/known_hosts

      - name: Deploy to server through sftp
        run: |
          lftp -u ${{ secrets.OVH_FTP_USER }},${{ secrets.OVH_FTP_PASSWORD }} -p 22 -e "mirror -R --verbose --delete --exclude .htaccess ./public/ www; bye" sftp://${{ secrets.SFTP_SERVER_NAME }}
